//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTRM.MyGoals.WEB.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalHistory
    {
        public System.Guid id { get; set; }
        public System.Guid idGoal { get; set; }
        public string description { get; set; }
        public System.DateTime includeDate { get; set; }
    
        public virtual Goal Goal { get; set; }
    }
}
